---
title: "GroupTask"
author: "Group1"
date: "20/02/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(data.table,tidyverse,lubridate,ggplot2, dply)

```
## Group Task 1
###The goal of the group task is to apply data science tools and techniques to improve a lending business. 
<!-- The two major use cases of the tasks include; Build a predictive model that can -->
<!-- classify a loan application as performing or non-performing Develop an -->
<!-- alternative credit scoring framework -->
<!-- Key areas to divide responsibilities: Data Visualisation, Data Modelling, Data -->
<!-- Preprocessing -->

```{r}
### All loans df
AllLoans <- fread('all_loans.csv', stringsAsFactors = F, drop = c('PRODUCT_NAME', 'CURRENCY'))
AllLoansdf <- AllLoans %>% group_by(CUSTOMER_UNIQUE_ID) %>% filter(BOOK_DATE == max(BOOK_DATE))

### All loans application
AllLoansApplication <- fread('all_loans_application.csv', drop = c('OFFERID','APPLICATION_STATUS', 'MODULE'))
AllLoansAppdf <- AllLoansApplication %>% group_by(CUSTOMER_UNIQUE_ID) %>% filter(DATE_OF_APPLY
 == max(DATE_OF_APPLY))

### All transaction digital imported in
AllTransactionsDigital <- fread('all_transactions_digital.csv', select = c('CUSTOMER_UNIQUE_ID','MASKED_ACCT','LCY_AMOUNT'))

#### AN aggregate of digital transactions
ATdf <- aggregate( AllTransactionsDigital$LCY_AMOUNT, by=list(CUSTOMER_UNIQUE_ID= AllTransactionsDigital$CUSTOMER_UNIQUE_ID), FUN=sum)

### All Accounts
AllAccountsDf <- read.csv('all_accounts.csv')

### All balance
AllBalancesDf <-fread('all_balances.csv')
#### All balance aggregate
AllBalancesDf <- aggregate( AllBalancesDf$BAL, by=list(CUSTOMER_UNIQUE_ID = AllBalancesDf$CUSTOMER_UNIQUE_ID, MASKED_ACCOUNT = AllBalancesDf$MASKED_ACCOUNT ), FUN=sum)

names(AllBalancesDf)[3] <- 'AggBal'

### All demographics
AllDemographics <- fread('all_demographics.csv',  stringsAsFactors = FALSE, sep = '|', header = TRUE, select = c('CUSTOMER_UNIQUE_ID', 'CUSTOMER_TYPE','MARITAL_STATUS','DATE_OF_BIRTH', 'SEX') )

AllInvestmentsDf <- read.csv('all_investments.csv')


### BUREAU SCORE
BureauScore <- fread('bureau_score.csv', drop = c('CUSTOMER_TYPE', 'BUREAU_SCORE', 'CPO','LOAN_CT'))
BSDF <- aggregate( BureauScore$APPROVED_AMT, by=list(CUSTOMER_UNIQUE_ID= BureauScore$CUSTOMER_UNIQUE_ID, APPROVE_AMT= BureauScore$APPROVED_AMT), FUN=sum)

length(unique(BureauScore$CUSTOMER_UNIQUE_ID)) 
length(unique(AllAccountsDf$CUSTOMER_UNIQUE_ID))
length(unique(AllTransactionsDigital$CUSTOMER_UNIQUE_ID))
# ddply(AllAccountsDf, "Species", summarise, 
#   wmn = weighted.mean(Sepal.Length, Petal.Length),
#   mn = mean(Sepal.Length))


# glimpse(AllAccountsDf)
# str(AllAccountsDf)
# str(AllBalancesDf)
# AllBalancesDf$VAL_DT <- mdy( as.character(AllBalancesDf$VAL_DT) )
# str(AllDemographicsDf)

```


```{r}

df <- left_join(AllAccountsDf, AllBalancesDf, by = c('MASKED_ACCOUNT','CUSTOMER_UNIQUE_ID'))
df <- left_join(df, AllDemographicsDf, by = 'CUSTOMER_UNIQUE_ID')
df <- left_join(df, AllInvestmentsDf,by = c('CUSTOMER_UNIQUE_ID','MASKED_ACCOUNT') )

glimpse(df)
ncol(df)
```

we have 29,057

